# Generated by Django 5.0 on 2024-01-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zikr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('meaning', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
