# Generated by Django 5.0.1 on 2024-01-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrs', '0002_zikr_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='zikr',
            name='count_val',
            field=models.IntegerField(default=0),
        ),
    ]
