# Generated by Django 5.0.1 on 2024-02-01 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrs', '0003_zikr_count_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='zikr',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
