# Generated by Django 5.0.1 on 2024-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrs', '0004_zikr_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='zikr',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
